### PR TITLE
Digging into COCO

### PR DESCRIPTION
**Pull request by benjaminpkane**

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Ready for review. This should be consistent with the medium draft now.

**Comment by brimoor** [comment]
@benjaminpkane there's some new instructions in `CONTRIBUTING.md` for how to add new examples (will populate README with appropriate links)

**Comment by benjaminpkane** [comment]
My mistake. Fixed.

**Review by brimoor — APPROVED** [review]
Really thorough work here! LGTM

Here's a couple suggestions for your consideration:

- I like to put all App-launching commands in a separate cell to mitigate any scrolling issues that may occur if there's too much text output in the same cell and the user hasn't configured their notebook settings appropriately. In this case, that would mean moving `launch_app()` into its own cell away from `load_zoo_dataset()`

- The `apply_model()` cell shows that the operation took 30 minutes, which is a fair amount of time for a user to wait. I recommend adding a commented out command explaining that if you don't have GPU access, then consider adding a `.take()` stage or similar to make things run faster

**Pull request merged**
