### PR TITLE
Updating quickstart and walkthrough to use new evaluation framework

### PR DESCRIPTION
**Pull request by brimoor**
Updates the quickstart and walkthrough notebooks to use the new evaluation framework introduced in `fiftyone==0.7.3`.

These are important changes to get live because the latest release slightly changed some of the field names generated by the evaluation routine, which may confuse readers trying to follow along with the example.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
This is news to me, but detection `mistakenness` is now `mistakenness_loc`, correct? I think the "Finding label mistakes" section needs to be updated accordingly.

**Comment by brimoor** [comment]
Actually there is both `mistakenness` and `mistakenness_loc`. The quickstart only discusses `mistakenness`, but I think the content reads okay as is

**Comment by benjaminpkane** [comment]
The final view yields no results for me at the moment because it does not use `mistakennes_loc

**Comment by brimoor** [comment]
oh I see. I didn't re-run the last cell b/c I thought nothing needed to be changed. Wrong! I'll fix it

**Comment by brimoor** [comment]
@benjaminpkane Hmm actually I wasn't able to reproduce the empty output that you mentioned. I did re-generate the last output, but I didn't need to change any code to get the same results as before... 🤔

**Review by benjaminpkane — APPROVED** [review]
Approving, but I still think there is an issue. It is confusing to me that you have `mistakenness` on your detections, but I do not get that when I run it. I have `v0.3.0` brain installed.

Screenshot from 2021-02-23 17-37-01

My output:
Screenshot from 2021-02-23 17-38-31

**Comment by brimoor** [comment]
Oooooh I think I know what the problem is. As of the last prod release, the mistakenness brain method runs evaluation with `eval_key=mistakenness`, which conflicts with the brain results (both are writing stuff under a `mistakenness` key. The last step of detection mistakenness is to clean up the evaluation results, which deletes the field from the dataset.

tl; dr- mistakenness is currently broken in production. I discovered this issue in my recent brain work but didn't realize it was also a problem in production.

**Comment by brimoor** [comment]
The bug is unrelated to this PR, so I'll go ahead and merge this one.

**Pull request merged**
